spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 82808972282-dp4f9a8e7kp4sf1l20ikef4jqdorfb4p.apps.googleusercontent.com
            client-secret: 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
            scope: profile, email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            client-name: Google
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub
server:
  port: 8080