spring:
 datasource:
  url: jdbc:mysql://localhost:3306/authtestdb
  username: authuser
  password: authuser
  driver-class-name: com.mysql.cj.jdbc.Driver
 security:
  oauth2:
   resourceserver:
    opaque-token:
     introspection-uri: "https://www.googleapis.com/oauth2/v3/userinfo"
     clientId: "${clientId}"
     clientSecret: "${clientSecret}"

